In [26]:
#Task 1: Lexicons
#Task 2: Collection of words/phrases + information

# Stopwords
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [27]:
stopwords.words('hindi')

OSError: No such file or directory: 'C:\\Users\\Sumit\\AppData\\Roaming\\nltk_data\\corpora\\stopwords\\hindi'

In [28]:
# CPU wordlist
import nltk
entries = nltk.corpus.cmudict.entries()
len(entries)


133737

In [29]:
entries[:100]

[('a', ['AH0']),
 ('a.', ['EY1']),
 ('a', ['EY1']),
 ('a42128',
  ['EY1',
   'F',
   'AO1',
   'R',
   'T',
   'UW1',
   'W',
   'AH1',
   'N',
   'T',
   'UW1',
   'EY1',
   'T']),
 ('aaa', ['T', 'R', 'IH2', 'P', 'AH0', 'L', 'EY1']),
 ('aaberg', ['AA1', 'B', 'ER0', 'G']),
 ('aachen', ['AA1', 'K', 'AH0', 'N']),
 ('aachener', ['AA1', 'K', 'AH0', 'N', 'ER0']),
 ('aaker', ['AA1', 'K', 'ER0']),
 ('aalseth', ['AA1', 'L', 'S', 'EH0', 'TH']),
 ('aamodt', ['AA1', 'M', 'AH0', 'T']),
 ('aancor', ['AA1', 'N', 'K', 'AO2', 'R']),
 ('aardema', ['AA0', 'R', 'D', 'EH1', 'M', 'AH0']),
 ('aardvark', ['AA1', 'R', 'D', 'V', 'AA2', 'R', 'K']),
 ('aaron', ['EH1', 'R', 'AH0', 'N']),
 ("aaron's", ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aarons', ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aaronson', ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ('aaronson', ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ("aaronson's", ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z']),
 ("aaronson's", ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z'

In [30]:
#Wordnet
from nltk.corpus import wordnet as wn
wn.synsets('vehicle')

[Synset('vehicle.n.01'),
 Synset('vehicle.n.02'),
 Synset('vehicle.n.03'),
 Synset('fomite.n.01')]

In [31]:
wn.synset('vehicle.n.01').lemma_names()

['vehicle']

In [32]:
wn.synset('vehicle.n.02').lemma_names()

['vehicle']

In [33]:
wn.synset('fomite.n.01').lemma_names()

['fomite', 'vehicle']

In [34]:
wn.synset('bus.n.01').lemma_names()

['bus',
 'autobus',
 'coach',
 'charabanc',
 'double-decker',
 'jitney',
 'motorbus',
 'motorcoach',
 'omnibus',
 'passenger_vehicle']

In [42]:
wn.synset('car.n.01').lemma_names()

['car', 'auto', 'automobile', 'machine', 'motorcar']

In [35]:
from nltk.corpus import wordnet as wn
wn.synsets('good')

[Synset('good.n.01'),
 Synset('good.n.02'),
 Synset('good.n.03'),
 Synset('commodity.n.01'),
 Synset('good.a.01'),
 Synset('full.s.06'),
 Synset('good.a.03'),
 Synset('estimable.s.02'),
 Synset('beneficial.s.01'),
 Synset('good.s.06'),
 Synset('good.s.07'),
 Synset('adept.s.01'),
 Synset('good.s.09'),
 Synset('dear.s.02'),
 Synset('dependable.s.04'),
 Synset('good.s.12'),
 Synset('good.s.13'),
 Synset('effective.s.04'),
 Synset('good.s.15'),
 Synset('good.s.16'),
 Synset('good.s.17'),
 Synset('good.s.18'),
 Synset('good.s.19'),
 Synset('good.s.20'),
 Synset('good.s.21'),
 Synset('well.r.01'),
 Synset('thoroughly.r.02')]

In [36]:
#Task 2
def gender_features(word):
    return {'last_letter':word[-1]}

In [43]:
gender_features('Obama')

{'last_letter': 'a'}

In [44]:
gender_features('Trump')

{'last_letter': 'p'}

In [38]:
from nltk.corpus import names
labeled_names = ([(name, 'male') for name in names.words('male.txt')]+
[(name, 'female') for name in names.words('female.txt')])

In [39]:
import random
random.shuffle(labeled_names)

In [47]:
featureset = [(gender_features(n), gender) for (n,gender) in labeled_names]

In [49]:
train_set, test_set = featureset[500:], featureset[:500]

In [75]:
import nltk
classifier = nltk.NaiveBayesClassifier.train(train_set)


In [76]:
classifier.classify(gender_features('David'))

'male'

In [77]:
classifier.classify(gender_features('Obama'))

'female'

In [78]:
classifier.classify(gender_features('Sumit'))

'male'

In [79]:
classifier.classify(gender_features('Rakesh'))

'female'

In [80]:
classifier.classify(gender_features('Smith'))

'female'

In [81]:
print(nltk.classify.accuracy(classifier, test_set))

0.76


In [55]:
# Task 3: Vectorisers & cosine similarity
from sklearn.feature_extraction.text import CountVectorizer

In [56]:
vect = CountVectorizer(binary = True)
corpus = ["Tessaract is good character recognition engine", "optical character recognition is significant"]
vect.fit(corpus) # It will do some indexing to uniqe words in given text

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [57]:
vocab = vect.vocabulary_ #Inbuit function to create vocabulary of unique wrods

In [58]:
for key in sorted(vocab.keys()):
    print("{}:{}".format(key, vocab[key]))

character:0
engine:1
good:2
is:3
optical:4
recognition:5
significant:6
tessaract:7


In [59]:
print(vect.transform(["This is good optical illusion"]).toarray())

[[0 0 1 1 1 0 0 0]]


In [60]:
print(vect.transform(corpus).toarray())

[[1 1 1 1 0 1 0 1]
 [1 0 0 1 1 1 1 0]]


In [61]:
from sklearn.metrics.pairwise import cosine_similarity

In [62]:
similarity = cosine_similarity(vect.transform(["Google Cloud Vision is a character recognition engine"]).toarray(), vect.transform(["OCR is an optical character recognition engine"]).toarray())

In [63]:
print(similarity)

[[0.89442719]]


## Homework

In [64]:
# Vectorisers & cosine similarity
from sklearn.feature_extraction.text import CountVectorizer

In [65]:
vect = CountVectorizer(binary = True)

from nltk.corpus import inaugural
inaugural.fileids()
corpus = inaugural.words(fileids='2001-Bush.txt')[:1000]
corpus1 = inaugural.words(fileids='2009-Obama.txt')[:1000]
#corpus = [""]
vect.fit(corpus) # It will do some indexing to uniqe words in given text

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [66]:
vocab = vect.vocabulary_ #Inbuit function to create vocabulary of unique wrods

In [67]:
for key in sorted(vocab.keys()):
    print("{}:{}".format(key, vocab[key]))

225:0
above:1
accept:2
accomplishment:3
across:4
affirm:5
afford:6
after:7
all:8
allies:9
allow:10
along:11
also:12
am:13
ambitions:14
america:15
american:16
americans:17
an:18
and:19
apathy:20
appear:21
are:22
arrogance:23
as:24
at:25
authority:26
backgrounds:27
balance:28
be:29
bear:30
became:31
because:32
been:33
before:34
begin:35
beginnings:36
believe:37
belongs:38
best:39
beyond:40
birth:41
blessing:42
blood:43
born:44
bound:45
build:46
but:47
by:48
called:49
calling:50
can:51
carry:52
cause:53
century:54
challenge:55
chance:56
chaos:57
character:58
child:59
children:60
choice:61
choose:62
circumstances:63
citizen:64
citizens:65
civil:66
civility:67
claim:68
clear:69
clinton:70
come:71
commitment:72
common:73
community:74
compassion:75
concern:76
condemn:77
conducted:78
confident:79
confront:80
confronting:81
conquer:82
contest:83
continent:84
continue:85
country:86
courage:87
courageous:88
course:89
creates:90
creed:91
cynicism:92
dangers:93
dealing:94
debates:95
decline:96
deep

In [68]:
print(vect.transform(corpus).toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [69]:
from sklearn.metrics.pairwise import cosine_similarity

In [70]:
similarity = cosine_similarity(vect.transform(corpus).toarray(), vect.transform(corpus1).toarray())

In [71]:
print(similarity)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
